# Generated by Django 4.0.2 on 2022-02-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('1', 'Marketeer'), ('2', 'Cliente')], help_text='1 - Marketeer; 2 - Cliente;', max_length=1, verbose_name='Tipo do usuário.')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da pessoa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'ordering': ['-name'],
            },
        ),
    ]
