# Generated by Django 4.0.2 on 2022-02-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-name'], 'verbose_name': 'Pessoa'},
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome da pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('1', 'Marketeer'), ('2', 'Cliente')], help_text='1 - Marketeer; 2 - Cliente;', max_length=1, verbose_name='Tipo do usuário.'),
        ),
    ]
