# Generated by Django 4.0.2 on 2022-02-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiuser',
            options={'ordering': ['-name'], 'verbose_name': 'Usuário da API', 'verbose_name_plural': 'Usuários da API'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
