# Generated by Django 4.0.2 on 2022-02-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_cnpj'),
        ('accounts', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='star_companies',
            field=models.ManyToManyField(related_name='star_company', to='company.Company'),
        ),
    ]
