# Generated by Django 4.0.2 on 2022-02-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_cnpj'),
        ('accounts', '0011_apiuser_star_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='star_companies',
            field=models.ManyToManyField(blank=True, related_name='star_company', to='company.Company'),
        ),
    ]
