# Generated by Django 4.0.2 on 2022-05-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_apiuser_star_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='telephone',
            field=models.CharField(default='', max_length=16, verbose_name='Telefone'),
        ),
    ]
