# Generated by Django 4.0.2 on 2022-03-24 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_crm', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='GoalPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_goal', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.product')),
            ],
            options={
                'verbose_name': 'Meta',
            },
        ),
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visualization', models.CharField(choices=[('1', 'Quantitativa'), ('2', 'Monetária')], default='1', max_length=2, verbose_name='Visualização')),
                ('begin_date', models.DateField(db_index=True)),
                ('_begin_date', models.DateField(blank=True, db_index=True, null=True)),
                ('periodicity', models.CharField(choices=[('1', 'Semanal'), ('2', 'Mensal'), ('3', 'Semestral'), ('4', 'Anual')], max_length=1, verbose_name='Seleção de Periodicidade')),
                ('repeat_periodicity', models.BooleanField(default=False)),
                ('segmentation', models.CharField(choices=[('1', 'Segmentada'), ('2', 'Não Segmentada')], default='1', max_length=2, verbose_name='Segmentação')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comercial.goalplanner')),
            ],
        ),
    ]
