# Generated by Django 4.0.2 on 2022-03-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(db_index=True)),
                ('_begin_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expiration_date', models.DateField(db_index=True)),
                ('periodicity', models.CharField(choices=[('1', 'Semanal'), ('2', 'Mensal'), ('3', 'Semestral'), ('4', 'Anual')], max_length=1, verbose_name='Seleção de Periodicidade')),
                ('repeat_periodicity', models.BooleanField(default=False)),
            ],
        ),
    ]
