# Generated by Django 4.0.2 on 2022-03-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercial',
            name='expiration_date',
        ),
    ]
