# Generated by Django 4.0.2 on 2022-08-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_comercial_visualization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='segmentation',
            field=models.CharField(choices=[('1', 'Segmentada'), ('2', 'Não Segmentada')], default=0, max_length=2, verbose_name='Segmentação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comercial',
            name='visualization',
            field=models.CharField(choices=[('1', 'Quantitativa'), ('2', 'Monetária')], default=0, max_length=2, verbose_name='Visualização'),
            preserve_default=False,
        ),
    ]
