# Generated by Django 4.0.2 on 2022-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_comercial_visualization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercial',
            name='visualization_quant',
            field=models.BooleanField(default=True, verbose_name='Visualização Quantitativa'),
        ),
    ]
