# Generated by Django 4.0.2 on 2022-03-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_remove_comercial_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='segmentation',
            field=models.CharField(choices=[('1', 'Segmentada'), ('2', 'Não Segmentada')], default='1', max_length=2, verbose_name='Segmentação'),
        ),
        migrations.AddField(
            model_name='comercial',
            name='visualization',
            field=models.CharField(choices=[('1', 'Quantitativa'), ('2', 'Monetária')], default='1', max_length=2, verbose_name='Visualização'),
        ),
    ]
