# Generated by Django 4.0.2 on 2022-04-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_remove_goalplanner_products_goalplanner_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalplanner',
            name='general_goal',
        ),
    ]
