# Generated by Django 4.0.2 on 2022-04-09 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0006_remove_goalplanner_product_goalplanner_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comercial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id_crm'], 'verbose_name': 'Produto'},
        ),
    ]
