# Generated by Django 4.0.2 on 2022-04-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0007_alter_comercial_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id_crm',
            field=models.CharField(max_length=50),
        ),
    ]
