# Generated by Django 4.0.2 on 2022-05-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0010_comercialhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComercialHistory',
        ),
    ]
