# Generated by Django 4.0.2 on 2022-06-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_created_at'),
        ('comercial', '0012_historicalproduct_historicalgoalplanner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercial',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='historicalcomercial',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
    ]
