# Generated by Django 4.0.2 on 2022-08-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_comercial_segmentation_comercial_visualization'),
        ('comercial', '0014_alter_comercial_company'),
    ]

    operations = [
    ]
