# Generated by Django 4.0.2 on 2022-08-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0015_merge_20220804_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcomercial',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical comercial'},
        ),
        migrations.AlterModelOptions(
            name='historicalgoalplanner',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Meta'},
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Produto'},
        ),
        migrations.AddField(
            model_name='historicalcomercial',
            name='visualization',
            field=models.CharField(choices=[('1', 'Quantitativa'), ('2', 'Monetária')], default='1', max_length=2, verbose_name='Visualização'),
        ),
        migrations.AlterField(
            model_name='comercial',
            name='segmentation',
            field=models.CharField(choices=[('1', 'Segmentada'), ('2', 'Não Segmentada')], default='1', max_length=2, verbose_name='Segmentação'),
        ),
        migrations.AlterField(
            model_name='comercial',
            name='visualization',
            field=models.CharField(choices=[('1', 'Quantitativa'), ('2', 'Monetária')], default='1', max_length=2, verbose_name='Visualização'),
        ),
        migrations.AlterField(
            model_name='historicalcomercial',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalgoalplanner',
            name='history_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='history_date',
            field=models.DateTimeField(),
        ),
    ]
