# Generated by Django 4.0.2 on 2022-08-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0016_alter_historicalcomercial_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercial',
            name='visualization',
        ),
        migrations.RemoveField(
            model_name='historicalcomercial',
            name='visualization',
        ),
    ]
