# Generated by Django 4.0.2 on 2022-08-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_alter_customquery_data_columns'),
        ('comercial', '0017_remove_comercial_visualization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
