# Generated by Django 4.0.2 on 2022-02-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(db_index=True, max_length=11, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Empresa')),
                ('logo', models.CharField(max_length=10)),
                ('db_name', models.CharField(max_length=100)),
            ],
        ),
    ]
