# Generated by Django 4.0.2 on 2022-02-28 18:55

import company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_company_db_name_customquery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customquery',
            options={'verbose_name': 'Query Personalizada'},
        ),
        migrations.AlterField(
            model_name='customquery',
            name='company_source',
            field=models.CharField(help_text='Nome da empresa no banco MySQL. Exemplo: sebraeal|sebrae', max_length=100),
        ),
        migrations.AlterField(
            model_name='customquery',
            name='datasource',
            field=models.CharField(help_text='Nome do social. Exemplo: googleads|facebookads|programatica', max_length=100),
        ),
        migrations.AlterField(
            model_name='customquery',
            name='db_name',
            field=models.CharField(help_text='Nome do Schema no banco MySql. Exemplo: client_data', max_length=100, validators=[company.models.CustomQuery.validate_db_name]),
        ),
    ]
