# Generated by Django 4.0.2 on 2022-03-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_customquery_datasource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customquery',
            options={'verbose_name': 'Query Personalizada', 'verbose_name_plural': 'Queries Personalizadas'},
        ),
    ]
