# Generated by Django 4.0.2 on 2022-03-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_customquery_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquery',
            name='query_type',
            field=models.CharField(choices=[('1', 'Campanha'), ('2', 'CRM'), ('3', 'CRM DEALS')], default='1', max_length=2),
        ),
    ]
