# Generated by Django 4.0.2 on 2022-03-31 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_customquery_query_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquery',
            name='query_type',
            field=models.CharField(choices=[('1', 'Campanha'), ('2', 'CRM')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='CustomMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(choices=[('1', 'Impressões'), ('2', 'Cliques'), ('3', 'Alcance'), ('4', 'Views de Vídeo/Áudio'), ('5', '25% Views de Vídeo/Áudio'), ('6', '50% Views de Vídeo/Áudio'), ('7', '75% Views de Vídeo/Áudio'), ('8', '100% Views de Vídeo/Áudio'), ('9', 'Custo')], max_length=2)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Métrica',
            },
        ),
    ]
