# Generated by Django 4.0.2 on 2022-04-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_customquery_query_type_custommetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommetrics',
            options={'verbose_name': 'Funil'},
        ),
        migrations.AddField(
            model_name='company',
            name='funil',
            field=models.CharField(choices=[('1', 'V'), ('2', 'Y')], default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='custommetrics',
            name='step',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], default='1', max_length=2),
        ),
    ]
