# Generated by Django 4.0.2 on 2022-04-04 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_custommetrics_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommetrics',
            name='step',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4)], default='1', max_length=2, verbose_name='Etapa'),
        ),
        migrations.CreateModel(
            name='CustomDatabaseColumns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_idclorus', models.BooleanField(default=False)),
                ('raw_tabledata', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.customquery')),
            ],
        ),
    ]
