# Generated by Django 4.0.2 on 2022-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_custommetrics_step_customdatabasecolumns'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquery',
            name='data_columns',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CustomDatabaseColumns',
        ),
    ]
