# Generated by Django 4.0.2 on 2022-04-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_customquery_data_columns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquery',
            name='data_columns',
            field=models.TextField(blank=True, help_text='Colunas da tabela separadas por vírgula. A primeira coluna tem que conter o idclorus. Exemplo: campaign_id, campaign_name', null=True),
        ),
    ]
