# Generated by Django 4.0.2 on 2022-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_customquery_data_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(),
        ),
    ]
