# Generated by Django 4.0.2 on 2022-05-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custommetrics',
            options={'verbose_name': 'Métricas do Funil', 'verbose_name_plural': 'Métricas do Funil'},
        ),
        migrations.AlterField(
            model_name='custommetrics',
            name='id_name',
            field=models.CharField(choices=[('1', 'Impressões'), ('2', 'Cliques'), ('3', 'Alcance'), ('4', 'Views de Vídeo/Áudio'), ('5', '25% Views de Vídeo/Áudio'), ('6', '50% Views de Vídeo/Áudio'), ('7', '75% Views de Vídeo/Áudio'), ('8', '100% Views de Vídeo/Áudio'), ('9', 'Custo'), ('10', 'Leads')], max_length=2, verbose_name='Escolha a Métrica'),
        ),
    ]
