# Generated by Django 4.0.2 on 2022-05-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_custommetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommetrics',
            name='step',
            field=models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)], default='1', max_length=2, verbose_name='Etapa'),
        ),
    ]
