# Generated by Django 4.0.2 on 2022-06-10 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customquery',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
