# Generated by Django 4.0.2 on 2022-06-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_customquery_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customquery',
            name='data_columns',
            field=models.TextField(blank=True, help_text='Colunas da tabela separadas por vírgula. Ordem das colunas idclorus, ad_id [,...]. Exemplo: Campaign, `Ad ID` | Creative_Set', null=True),
        ),
    ]
