# Generated by Django 4.0.2 on 2022-05-21 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0021_alter_custommetrics_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clorus_id', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nome da Campanha')),
                ('image', models.TextField(default='')),
                ('goal', models.CharField(choices=[('1', 'Tráfego'), ('2', 'Reconhecimento de marca'), ('3', 'Engajamento'), ('4', 'Geração de lead'), ('5', 'Vendas')], default='', max_length=2, verbose_name='Objetivo da Campanha')),
                ('goal_description', models.TextField(default='', verbose_name='Descrição do Objetivo')),
                ('goal_budget', models.CharField(default='', max_length=255, verbose_name='Meta (Total proveniente de Meta Geral)')),
                ('budget', models.CharField(default='', max_length=255, verbose_name='Valor Investido')),
                ('last_change', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('description', models.TextField()),
                ('hypothesis', models.TextField()),
                ('result', models.TextField()),
                ('result_type', models.CharField(choices=[('1', 'Negativo'), ('2', 'Positivo'), ('3', 'Neutro')], max_length=2)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMetaDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_crm', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('custom_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.customquery')),
            ],
            options={
                'verbose_name': 'Detalhes de Campanha',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_details',
            field=models.ManyToManyField(to='campaigns.CampaignMetaDetail'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='custom_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.customquery'),
        ),
    ]
