# Generated by Django 4.0.2 on 2022-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='budget',
            field=models.CharField(default='1', max_length=255, verbose_name='Valor Investido'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal',
            field=models.CharField(choices=[('1', 'Colocar Opções')], default=1, max_length=2, verbose_name='Objetivo da Campanha'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_budget',
            field=models.CharField(default='1', max_length=255, verbose_name='Meta (Total proveniente de Meta Geral)'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='goal_description',
            field=models.TextField(default='1', verbose_name='Descrição do Objetivo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='1', max_length=255, verbose_name='Nome da Campanha'),
        ),
    ]
