# Generated by Django 4.0.2 on 2022-03-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_budget_campaign_goal_campaign_goal_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.CharField(choices=[('1', 'Tráfego'), ('2', 'Reconhecimento de marca'), ('3', 'Engajamento'), ('4', 'Geração de lead'), ('5', 'Vendas')], default=1, max_length=2, verbose_name='Objetivo da Campanha'),
        ),
    ]
