# Generated by Django 4.0.2 on 2022-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_goal_quantity_alter_campaign_custom_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='goal_budget',
            field=models.CharField(default='', max_length=255, verbose_name='Soma de valor monetário (Total proveniente de Meta Geral)'),
        ),
    ]
