# Generated by Django 4.0.2 on 2022-03-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_goal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
