# Generated by Django 4.0.2 on 2022-06-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimization',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='optimization',
            old_name='date',
            new_name='date_created',
        ),
    ]
