# Generated by Django 4.0.2 on 2022-04-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
        ('campaigns', '0004_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='comercial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comercial.comercial'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_description',
            field=models.TextField(default='', verbose_name='Descrição do Objetivo'),
        ),
    ]
