# Generated by Django 4.0.2 on 2022-04-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_comercial_alter_campaign_goal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome da Campanha'),
        ),
    ]
