# Generated by Django 4.0.2 on 2022-04-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.TextField(default='1'),
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('description', models.TextField()),
                ('hipothesys', models.TextField()),
                ('result', models.TextField()),
                ('result_type', models.CharField(choices=[('1', 'Negativo'), ('2', 'Positivo'), ('3', 'Neutro')], max_length=2)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
        ),
    ]
