# Generated by Django 4.0.2 on 2022-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_criativos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criativos',
            name='channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criativos',
            name='format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criativos',
            name='goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
