# Generated by Django 4.0.2 on 2022-04-09 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_image_optimization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimization',
            old_name='hipothesys',
            new_name='hypothesis',
        ),
    ]
