# Generated by Django 4.0.2 on 2022-04-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_rename_hipothesys_optimization_hypothesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimization',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='last_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
