# Generated by Django 4.0.2 on 2022-06-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_criativos_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='date_created',
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
