# Generated by Django 4.0.2 on 2022-04-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_options_campaign_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='clorus_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.CharField(default='', max_length=255, verbose_name='Valor Investido'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal',
            field=models.CharField(choices=[('1', 'Tráfego'), ('2', 'Reconhecimento de marca'), ('3', 'Engajamento'), ('4', 'Geração de lead'), ('5', 'Vendas')], default='', max_length=2, verbose_name='Objetivo da Campanha'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='goal_budget',
            field=models.CharField(default='', max_length=255, verbose_name='Meta (Total proveniente de Meta Geral)'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
