# Generated by Django 4.0.2 on 2022-06-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_campaign_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='funil_ids',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='optimization',
            name='title',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='campaign',
            name='clorus_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='date_created',
            field=models.DateField(db_index=True),
        ),
    ]
