# Generated by Django 4.0.2 on 2022-06-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_campaign_funil_ids_optimization_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criativos',
            name='ad_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='criativos',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
