# Generated by Django 4.0.2 on 2022-04-27 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_alter_company_logo'),
        ('campaigns', '0012_remove_campaign_company_campaign_custom_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='custom_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.customquery'),
        ),
    ]
