# Generated by Django 4.0.2 on 2022-06-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0013_alter_criativos_ad_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criativos',
            name='ad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
