# Generated by Django 4.0.2 on 2022-07-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_alter_criativos_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='criativos',
            name='cpv_goal',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='criativos',
            name='view_goal',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
