# Generated by Django 4.0.2 on 2022-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_criativos_cpv_goal_criativos_view_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criativos',
            name='cpv_goal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='criativos',
            name='view_goal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
